# Generated by Django 5.2.1 on 2025-07-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_slug', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
