# Generated by Django 4.2 on 2025-07-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='tariffs/images/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tariffs/icons/')),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('holiday', models.CharField(blank=True, max_length=255, null=True)),
                ('weekday', models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
