# Generated by Django 4.2 on 2025-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0004_product_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
    ]
