# Generated by Django 4.2 on 2025-08-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0005_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='brand',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
