# Generated by Django 4.2 on 2025-08-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0007_solarpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
