# Generated by Django 4.2 on 2025-08-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0008_product_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='memory',
            new_name='tag',
        ),
    ]
